{
 "title": "Island Inventory",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "island_id", "label": "Island Inventory", "query": { "query": "label_values(island_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Island Inventory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "island_inventory_resource{island_id=\"$island_id\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Island Production",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "island_production_resource{island_id=\"$island_id\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Island Consumption",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "island_consumption_resource{island_id=\"$island_id\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  }
 ]
}